### PR TITLE
testing: lints partial fixes

### PR DESCRIPTION
**Pull request by ccamacho**
This commit resolves the following lint rules:

- 'var-naming[no-reserved]'
- 'var-naming[no-role-prefix]'
- 'var-naming[pattern]'
- 'yaml[colons]'
- 'yaml[commas]'
- 'yaml[comments]'
- 'yaml[empty-lines]'
- 'yaml[indentation]'
- 'yaml[key-duplicates]'
- 'yaml[line-length]'
- 'yaml[octal-values]'
- 'name[template]'
- 'name[casing]'

Partially-solves: openshift-psap#10

### CODE REVIEW

**Comment by kpouget** [comment]
thanks @ccamacho , looks all good :) 
I only had one question ... but I found the answer 🙃 
```
* name[template] - Jinja templates should only be at the end of 'name'. This helps with the identification of tasks inside the source code when they fail. The use of templating inside name keys is discouraged as there are multiple cases where the rendering of the name template is not possible.
```
I'll launch a test run just to be on the safe side

**Comment by kpouget** [comment]
@ccamacho, [not a flake](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_topsail/22/pull-ci-openshift-psap-topsail-main-watsonx-serving-light/1696419731898109952/artifacts/light/prepare/artifacts/000__cluster__set_scale/_ansible.log) this time:
```
2023-08-29 07:38:43,813 p=271 u=psap-ci-runner n=ansible | 
2023-08-29 07:38:43,813 p=271 u=psap-ci-runner n=ansible | ---
2023-08-29 07:38:43,813 p=271 u=psap-ci-runner n=ansible | roles/cluster/cluster_set_scale/tasks/main.yml:74
2023-08-29 07:38:43,813 p=271 u=psap-ci-runner n=ansible | TASK: cluster_set_scale : Get first machineset
2023-08-29 07:38:43,813 p=271 u=psap-ci-runner n=ansible | ----- FAILED ----
2023-08-29 07:38:43,814 p=271 u=psap-ci-runner n=ansible | msg: Unexpected templating type error occurred on (Change all {{ machineset_instance_type + 'machinesets replicas to have sum' + scale }}): can only concatenate str (not "int") to str
2023-08-29 07:38:43,814 p=271 u=psap-ci-runner n=ansible | ----- FAILED ----
```

**Comment by ccamacho** [comment]
From the (CI job) [https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift-psap_topsail/22/pull-ci-openshift-psap-topsail-main-watsonx-serving-light/1696419731898109952/build-log.txt] the cast was failing with:

```
---
roles/cluster/cluster_set_scale/tasks/main.yml:74
TASK: cluster_set_scale : Get first machineset
----- FAILED ----
msg: Unexpected templating type error occurred on (Change all {{ machineset_instance_type + 'machinesets replicas to have sum' + scale }}): can only concatenate str (not "int") to str
----- FAILED ----
PLAY RECAP *********************************************************************
localhost                  : ok=18   changed=13   unreachable=0    failed=1    skipped=9    rescued=0    ignored=0   
---
```

**Comment by ccamacho** [comment]
> @ccamacho, [not a flake](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_topsail/22/pull-ci-openshift-psap-topsail-main-watsonx-serving-light/1696419731898109952/artifacts/light/prepare/artifacts/000__cluster__set_scale/_ansible.log) this time:
> 
> ```
> 2023-08-29 07:38:43,813 p=271 u=psap-ci-runner n=ansible | 
> 2023-08-29 07:38:43,813 p=271 u=psap-ci-runner n=ansible | ---
> 2023-08-29 07:38:43,813 p=271 u=psap-ci-runner n=ansible | roles/cluster/cluster_set_scale/tasks/main.yml:74
> 2023-08-29 07:38:43,813 p=271 u=psap-ci-runner n=ansible | TASK: cluster_set_scale : Get first machineset
> 2023-08-29 07:38:43,813 p=271 u=psap-ci-runner n=ansible | ----- FAILED ----
> 2023-08-29 07:38:43,814 p=271 u=psap-ci-runner n=ansible | msg: Unexpected templating type error occurred on (Change all {{ machineset_instance_type + 'machinesets replicas to have sum' + scale }}): can only concatenate str (not "int") to str
> 2023-08-29 07:38:43,814 p=271 u=psap-ci-runner n=ansible | ----- FAILED ----
> ```

xD Sorry didnt see this msg :)

**Comment by kpouget** [comment]
something wrong happened with the (my) [code](https://github.com/openshift-psap/topsail/blob/main/testing/utils/openshift_ci/pr_args.sh) parsing the GH comments :/ I'll have to turn this into Python sooner or later

**Comment by kpouget** [comment]
oh, I get it now, I thought the script was catching _my_ comment `not a flake this time`, but it's catching *yours*, as expected 😅 . Well, not really as expected, because it should search for the `/test watsonx-serving-light` prefix 🤔 

Can you launch the test, without anything else in the comment?

**Comment by ccamacho** [comment]
The ci/prow/watsonx-serving-light job [Passed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-psap_topsail/22/pull-ci-openshift-psap-topsail-main-watsonx-serving-light/1696445536061624320) I will rebase this as it is ood.

**Comment by kpouget** [comment]
thanks for your help @ccamacho, merging the PR :)

**Pull request merged**
