### PR TITLE
Update ansible lightspeed test to latest llm_load_test changes

### PR DESCRIPTION
**Pull request by dagrayvid**

### CODE REVIEW

**Comment by dagrayvid** [comment]
Rebased and updated to v0.30.0 runtime. Will do the short test again:

/test lightspeed-load-test-light

**Comment by dagrayvid** [comment]
/test lightspeed-load-test

cluster creation failed

**Comment by dagrayvid** [comment]
Testing runtime v0.31 with PT2_COMPILE:
/test lightspeed-load-test

**Comment by dagrayvid** [comment]
Missed namespace in runtime_config configmap. 

/test lightspeed-load-test

**Comment by dagrayvid** [comment]
Previously we redeployed the model between every test case even when the replicas of the model Pods were unchanged. With the 20 minute delay of PT2 compile, this takes too long.

/test lightspeed-load-test

**Comment by kpouget** [comment]
@dagrayvid I think this PR can be closed as outdated

**Pull request closed without merging**
