### PR TITLE
Add an SSL layer to the cluster Minio endpoint

### PR DESCRIPTION
**Pull request by kpouget**
The `minio` changes have been originally introduced by Supraja Manda as part of https://github.com/openshift-psap/topsail/pull/407.

Merge them independently of her PR to ease the integration testing.

### CODE REVIEW

**Comment by kpouget** [comment]
[test passed for kserve](https://ci.app-svc-perf.corp.redhat.com/job/ExternalTeams/job/RHODS/job/topsail/1051/artifact/run/f23-h33-000-6018r.rdu2.scalelab.redhat.com/000_test_ci/)

**Comment by smandaRH** [comment]
Hi @kpouget

**Comment by kpouget** [comment]
[notebook test passed](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift-psap_topsail/441/pull-ci-openshift-psap-topsail-main-rhoai-light/1812949476990521344/artifacts/light/test/artifacts/004__plots/report_00_report:_error_report.html), merging

**Pull request merged**
