### PR TITLE
[pipelines] WIP: Iris Pipeline Example

### PR DESCRIPTION
**Pull request by drewrip**

### CODE REVIEW

**Comment by drewrip** [comment]
[iris pipeline](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift-psap_topsail/343/pull-ci-openshift-psap-topsail-main-rhoai-e2e/1778524487491260416/artifacts/e2e/test/artifacts/000__pipelines_run_many/000__local_ci__run_multi/artifacts/ci-pod-0/004__pipelines__capture_state/pods/iris-training-pipeline-kzlj7-1197340696.log) now working with DSPv2

**Comment by drewrip** [comment]
[hello-world default pipeline](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift-psap_topsail/343/pull-ci-openshift-psap-topsail-main-rhoai-e2e/1778782305179930624/artifacts/e2e/test/artifacts/000__pipelines_run_many/000__local_ci__run_multi/artifacts/ci-pod-0/004__pipelines__capture_state/pods/multi-stage-execution-pipeline-jfmx6-105054967.log) also passing now

**Comment by kpouget** [comment]
@drewrip , please don't forget to check the linter, you have a `yes` to turn into `true`

**Comment by drewrip** [comment]
[pi pipeline is passing](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift-psap_topsail/343/pull-ci-openshift-psap-topsail-main-rhoai-light/1780657188222537728/artifacts/light/test/artifacts/000__pipelines_run_many/000__local_ci__run_multi/logs/ci-artifacts-0-qfx2n.log)

**Comment by drewrip** [comment]
[hash pipeline passed](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift-psap_topsail/343/pull-ci-openshift-psap-topsail-main-rhoai-light/1781071023374864384/artifacts/light/test/artifacts/000__pipelines_run_many/000__local_ci__run_multi/artifacts/ci-pod-0/003__pipelines__run_kfp_notebook/_ansible.log)

**Comment by drewrip** [comment]
[timed multi stage pipeline passed](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift-psap_topsail/343/pull-ci-openshift-psap-topsail-main-rhoai-light/1781347347377164288/artifacts/light/test/artifacts/000__pipelines_run_many/000__local_ci__run_multi/logs/ci-artifacts-0-t442m.log), all pipelines are updated and passing!

**Pull request closed without merging**
