### PR TITLE
Move toolbox to become the main topsail folder

### PR DESCRIPTION
**Pull request by ccamacho**
This commit renames the current toolbox folder to be the main topsail folder for all the cli options.

### CODE REVIEW

**Comment by kpouget** [comment]
thanks @ccamacho , I'll confirm that notebooks and watsonx-serving tests pass before mergin!

**Comment by kpouget** [comment]
* [expected failure](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_topsail/106/pull-ci-openshift-psap-topsail-main-notebooks-light/1725156435802722304/artifacts/light/test/artifacts/002__plots/report_00_report:_error_report.html) for the notebook test, under investigation by RHODS team
* [test passed for watsonx-serving](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_topsail/106/pull-ci-openshift-psap-topsail-main-watsonx-serving-light/1725156435848859648/artifacts/light/test/artifacts/report_index.html)
good to merge @ccamacho
/approve
/lgtm
/hold <-- unhold when you want to merge!

**Comment by ccamacho** [comment]
I just rebased the PR with the latest head

**Pull request merged**
