### PR TITLE
Keep limits_equals_requests true as default

### PR DESCRIPTION
**Pull request by npalaska**

### CODE REVIEW

**Comment by npalaska** [comment]
[Test](quickhttps://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift-psap_topsail/270/pull-ci-openshift-psap-topsail-main-rhoai-light/1766257757280800768/artifacts/light/test/) succeeded with kserve quick

**Comment by npalaska** [comment]
Test passed with kserve quick_raw (tgis only) https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift-psap_topsail/270/pull-ci-openshift-psap-topsail-main-rhoai-light/1766272367148929024/artifacts/light/test/

**Comment by kpouget** [comment]
thanks @npalaska , merging

**Pull request merged**
