### PR TITLE
[kserve] Update set of models

### PR DESCRIPTION
**Pull request by dagrayvid**
Update set of models and a few other fixes

### CODE REVIEW

**Comment by kpouget** [comment]
@dagrayvid ,
```
 [kserve] [temporary commit] add mixtral only preset
```
if you name your commit `WIP: <something>` , the github actions will block the merge. I like to have that to make sure that I don't merge WIP commits by mistake ([eg](https://github.com/openshift-psap/topsail/pull/423/commits))

**Comment by dagrayvid** [comment]
We ran the 2.12 TGIS and vLLM tests from this branch and all looks good. merging

**Pull request merged**
