### PR TITLE
rhoai dashboard ui scale test

### PR DESCRIPTION
**Pull request by smanda99**

### CODE REVIEW

**Comment by kpouget** [comment]
@smandaRH , can this PR be merged?

**Comment by smandaRH** [comment]
@kpouget i would like to work more on this PR.

**Comment by kpouget** [comment]
@smanda99 , please always update with `Rebase`
(update with `Merge` messes up with the history line)

**Comment by smanda99** [comment]
sure! kevin.

**Comment by kpouget** [comment]
Hello @smanda99 , could you rebase this PR so that we can merge this?

**Comment by smanda99** [comment]
Hi @kpouget,

Thanks for the update! I've rebased the PR, and it's ready to be merged from my side.

**Comment by kpouget** [comment]
merging the version for testing with 2.16

**Pull request merged**
