### PR TITLE
Prepare for OpenShift AI `2.13.0 RC1` regression testing

### PR DESCRIPTION
**Pull request by mcharanrm**
OpenShift AI 2.13.0 RC1 is available for Regression Testing.

### CODE REVIEW

**Comment by mcharanrm** [comment]
This is attempt to launch the smoke test for RHOAI 2.13.0 RC1 in the OpenShift CI cluster just to make sure there isn't any functional issue.

/test rhoai-light kserve vllm_cpt_single_model_gating_light

**Comment by mcharanrm** [comment]
CI [Job](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift-psap_topsail/477/pull-ci-openshift-psap-topsail-main-rhoai-light/1830990264399826944) is successful.

**Comment by kpouget** [comment]
thanks Charan, good to merge.
Please, when sharing the test link, give the URL to the [report index](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift-psap_topsail/477/pull-ci-openshift-psap-topsail-main-rhoai-light/1830990264399826944/artifacts/light/test/artifacts/report_index.html), or anything more relevant to the PR

**Comment by kpouget** [comment]
I merge this PR, so that I can put mine on top of it.

**Pull request merged**
